name: Documentation
on:   
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Doc Version
        run: |
          cd docs
          bash check_doc_version.bash 
